# Generated by Django 4.0.4 on 2022-07-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_alter_answers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaires',
            name='description',
            field=models.TextField(default='decs', null=True),
        ),
    ]
