# Generated by Django 4.0.4 on 2022-08-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_questionnaires_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qid',
            field=models.IntegerField(null=True),
        ),
    ]
